-- ADICIONAR COLUNA DE STATUS PARA IMÓVEIS (PRONTO / EM CONSTRUÇÃO)
ALTER TABLE products ADD COLUMN IF NOT EXISTS property_status TEXT DEFAULT 'ready';

-- ATUALIZAR SCHEMA PARA QUE A VERCEL ENXERGE A MUDANÇA
NOTIFY pgrst, 'reload schema';
