-- SQL Scripts for Supabase SQL Editor

-- 1. Create Profiles table (extension of auth.users)
CREATE TABLE profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  username TEXT UNIQUE NOT NULL,
  display_name TEXT,
  role_title TEXT,
  profile_image TEXT,
  whatsapp TEXT,
  instagram TEXT,
  facebook TEXT,
  slug TEXT UNIQUE NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT (now()) NOT NULL
);

-- 2. Create Products table
CREATE TABLE products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users ON DELETE CASCADE NOT NULL,
  name TEXT NOT NULL,
  image TEXT,
  description TEXT,
  colors JSONB,
  consortium_image TEXT,
  has_liberacred BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT (now()) NOT NULL,
  price NUMERIC -- Adicionado campo de preço caso queira ser 100% operacional
);

-- 3. Set up Row Level Security (RLS)
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE products ENABLE ROW LEVEL SECURITY;

-- Profiles Policies
CREATE POLICY "Profiles viewable by everyone" ON profiles FOR SELECT USING (true);
CREATE POLICY "Users can edit own profile" ON profiles FOR UPDATE USING (auth.uid() = id);

-- Products Policies
CREATE POLICY "Products viewable by everyone" ON products FOR SELECT USING (true);
CREATE POLICY "Users can manage own products" ON products FOR ALL USING (auth.uid() = user_id);
